name: MSYS2 GCC Package

on:
  push:
#  schedule:
#    - cron: '30 2,8,15 * * *'
  workflow_dispatch:

jobs:
  msys2:
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update msys2
        run: ./update_msys2.ps1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mingw

      - name: Create MSYS2 tools 7z
        timeout-minutes: 10
        run:  ruby create_msys2_pkg.rb

      - name: upload asset
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_tag: 'msys2-gcc-pkgs'
          release_name: msys2
